# See output: https://github.com/henrik/qed/actions
# Set up from these instructions: https://github.com/erlef/setup-elixir

name: CI
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Matrix so we can reference in caches below: https://www.mitchellhanberg.com/ci-cd-with-phoenix-github-actions-and-gigalixir/
        # NOTE: Keep in sync with elixir_buildpack.config.
        elixir: [1.11.3]
        otp: [23.2.2]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    # Based on: https://github.com/actions/cache/blob/master/examples.md#elixir---mix
    # `restore-keys` lets us fall back to partially matching caches.
    - name: Restore deps cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    - name: Restore build cache
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    - name: Install deps
      run: mix deps.get
    - name: Run tests
      run: mix test
